apiVersion: v1 
kind: Pod 
metadata: 
    name: builder 
spec: 
    containers: 
      - name: controller  
        image: $RL_HYPOTHESIS_1_DOCKER_CONTROLLER_IMAGE 
        env: 
          - name: DOCKER_HOST 
            value: unix:///var/run/docker.sock
            #value: tcp://localhost:2375
          - name: JOB
            value: $RL_HYPOTHESIS_1_JOB 
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run 
      - name: dind-daemon 
        image: docker:1.12.6-dind 
        securityContext: 
            privileged: true 
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker 
          - name: docker-socket
            mountPath: /var/run
    volumes: 
      - name: docker-graph-storage 
        emptyDir: {}
      - name: docker-socket
        emptyDir: {}
