kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      nodeSelector:
        #<labelname>:value
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: spark-master
          image: $RL_HYPOTHESIS_1_DOCKER_IMAGE 
          command: ["/app/spark/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: N_WORKERS
              value: "$RL_HYPOTHESIS_1_N_WORKERS" 
          resources:
            requests:
              cpu: "100m"
              memory: "5Gi"
