kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker
spec:
  replicas: $RL_HYPOTHESIS_1_N_WORKERS 
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      nodeSelector:
        #<labelname>:value
        cloud.google.com/gke-nodepool: spark-worker
      containers:
        - name: spark-worker
          image: $RL_HYPOTHESIS_1_DOCKER_IMAGE 
          env:
            - name: JOB
              value: "5-wo"
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "3200m"
              memory: "17Gi"
            limits:
              cpu: "3700m"
              memory: "18Gi"
          volumeMounts:
          - mountPath: /dat
            name: dat-volume
      volumes:
      - name: dat-volume
        emptyDir: {} 
