kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker
spec:
  replicas: 5 
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: $RL_HYPOTHESIS_1_DOCKER_IMAGE 
          env:
            - name: JOB
              value: "0-de"
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "3500m"
              memory: "20Gi"
          volumeMounts:
          - mountPath: /dat
            name: dat-volume
      volumes:
      - name: dat-volume
        emptyDir: {} 
