kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker
spec:
  replicas: 5 
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: $RL_HYPOTHESIS_1_DOCKER_IMAGE 
          env:
            - name: JOB
              value: "5-wo"
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 1500m
