kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: HELM_DOCKER_IMAGE  
          command: ["/app/spark/spark-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
